[package]
name = "forestry"
description = "A simple cross-platform CLI logging library for Rust"
version = "1.11.0"
edition = "2021"
authors = ["uptu <uptu@uptu.dev>"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/uptudev/forestry"
repository = "https://github.com/uptudev/forestry"
readme = "README.md"
keywords = ["logging", "cli", "console", "color", "string"]

[features]
async = ["tokio"]
static = []

[dependencies]
textfmt = "1.1.0"
supports-color = "3.0.2"

[dependencies.tokio]
version = "1.52"
features = ["rt", "io-std", "io-util", "fs", "macros"]
optional = true
